# Generated by Django 5.2.1 on 2025-07-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiones', '0002_bus_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='comidas_tipicas',
            field=models.TextField(default='desconocido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='costumbres',
            field=models.TextField(default='desconocido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='regiones/'),
        ),
        migrations.AddField(
            model_name='region',
            name='lugares_turisticos',
            field=models.TextField(default='desconocido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='tradiciones',
            field=models.TextField(default='desconocido'),
            preserve_default=False,
        ),
    ]
