# Generated by Django 5.2.1 on 2025-07-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiones', '0003_region_comidas_tipicas_region_costumbres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='comidas_tipicas',
            field=models.TextField(default='Desconocido'),
        ),
        migrations.AlterField(
            model_name='region',
            name='costumbres',
            field=models.TextField(default='Desconocido'),
        ),
        migrations.AlterField(
            model_name='region',
            name='lugares_turisticos',
            field=models.TextField(default='Desconocido'),
        ),
        migrations.AlterField(
            model_name='region',
            name='tradiciones',
            field=models.TextField(default='Desconocido'),
        ),
    ]
