# Generated by Django 5.2.4 on 2025-07-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regiones', '0004_alter_region_comidas_tipicas_alter_region_costumbres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='costumbres',
        ),
        migrations.RemoveField(
            model_name='region',
            name='recursos_turisticos',
        ),
    ]
