# Generated by Django 5.2.4 on 2025-07-29 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiones', '0005_remove_region_costumbres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='acerca_de',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='FotoRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria_regiones/')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='regiones.region')),
            ],
        ),
    ]
